### PR TITLE
TicTacToe Milestone 3: Game Logic

### PR DESCRIPTION
**Pull request by jonathastavares**
In this milestone we added:

- Game Logic
- Refactor main.rb
- Classes for the game, players, and computers.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
## Status: Changes Required

### Hello team,

**Great work on your project. However, there are a few fixes needed before the project can be approved.**

### Mandatory

1). **The game should be between two players and not a player and computer.**

2). **The game flow is not properly executed. Here is why:**

- **When I draw a game it returns an error instead of a message that the game is a tie.**

- **It doesn't throw an error when the player's name input is empty.**

- **The first game move is always made whether I insert a wrong value or press enter with no value given.**

- **When you change to two players, ensure a message displays who the next player is after a player move.**

3). **Remove all the inline comments in the files.**

### Happy coding 😃.

**PS: You can reach me on slack (Rose Wanjohi).**

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @jonathastavares and @janis-jenny :balloon: :lollipop: 

### Thank you for doing the changes requested by the previous reviewer, your Game works very well and is not breaking at any point I particularly like the fact that you request for players names I think this makes it more user friendly :video_game: :ok_hand:  and also that you ask the players if they know how to play so you only display the info if it's needed please feel proud of your hard work :clap: :clap: :clap:  there are still some changes to work on :construction: :construction_worker: :construction_worker_woman: 

#### Behaviour

- [x] The game is letting users put invalid numbers (larger than 9) and it's switching turns this is not correct, it is also not showing an invalid input message when getting an invalid input is just requesting for the player's input again

> Please add the validations so players can't input numbers larger than 9 and when an input is invalid put a proper message that tells the player their input wasn't correct and that's why they should enter it again

image

### Implementation details

- [x] DRY rule should be respected.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/dry.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

> Your Player and Computer classes are in essence the same class so get rid of one and reuse it for both players.

### That's it, team! :raised_hands: 

### Please :pray: do the changes :technologist: :woman_technologist:  and submit back for a code review when you are done :memo: 

### Happy coding! :rocket: 

Any questions ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

**Review by teekaytech — CHANGES_REQUESTED** [review]
### Status: Changes Required :warning: :traffic_light:  

_I commend your efforts in fixing the changes required earlier. This project is almost there: we just have to take care of some little changes and we should be good to go :muscle:_

**[ BEHAVIOR ]**
- [x] **Kindly delete the `computer.rb` class.** It looks like it's redundant since you now have 2 players. Besides, the content is similar to that of the player. Deleting it ensures that you Do-not Repeat Yourself.

**[ IMPLEMENTATION DETAILS ]**
- [x] **Also, when a player makes an invalid move, please add some information to tell the reason why the player is repeating his/her move.** Try to put a proper message that tells the player their input wasn't correct and that's why they should enter it again.

* * *
**Please make the changes above and submit another code review request when you're done.**

**I'm @taofeekolalere on slack.
Happy Coding :man_technologist:**

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__Good job on fixing the required changes. You might not have observed this, but you have a bug in your app I will try to make it simple for you to fix, but you can also reach out to me if you're in doubt.__

**[ REQUIRED CHANGES ]**

- [ ] **Your app is raising `ArgumentError` upon accepting player name.**
- In your player class, you're accepting just an argument in your `initialize` method, but when you created a new player instance, you're initialized the player class with two(2) arguments.

**player.rb**


**main.rb**


- You can either add the second argument to the `initialize` method of the `player.rb` class, OR
- You remove the second argument of the player instances in `main.rb`.
- Please test your game app carefully before you make another submission.

* * * 
**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on Twitter (@ola_lere), Github(@teekaytech), or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

**Review by mcrd25 — APPROVED** [review]
# Changes Approved :heavy_check_mark: 

Hi Team :wave: 

I am pleased to say your changes have been approved and you may merge and move on! :+1: 

--
Maya Douglas

**Pull request merged**
