### PR TITLE
Setup project

### PR DESCRIPTION
**Pull request by janis-jenny**
This is the first milestone of the Tic Tac Toe project.

I set up this files:

- .github\workflows
- bin
- lib
- .rubocop.yml

### CODE REVIEW

**Review by kitpao — CHANGES_REQUESTED** [review]
# 👋 Hello @janis-jenny 

I see you have properly set your linters and the Git Flow 🏅 nicely done. You are still missing some steps before your milestone can be approved, please check below to know the details 🔽 

- [x] For next commits, try to make them descriptive and don't repeat the names (at least specify what files you set up), as stated in [the article pointed in pathwright](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/)

- [x] Your file is not executable yet, it is missing the permissions. To grant them, please go back to the pathwright, and check the first steps of the guide (only to make it executable), [link here](https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/). **Hint:** In case you don't have a Linux environment, you can use this virtual workspace to use the commands, just append `gitpod.io/` to your repo URL, like this: https://gitpod.io/github.com/janis-jenny/TicTacToe/tree/setup-project
image

- [x] Your linters are not fixed yet, please correct them until you get a message similar to this one (Your errors are related to adding a new line at the end, and granting the permissions in the previous point):
image

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao
##### 🌟  If you have feedback about my reviews I would appreciate if can leave a recommendation in LinkedIn 💌 or let me know in Slack if you see improvements to be done 😛 

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

**Review by kubilaycaglayan — CHANGES_REQUESTED** [review]
Hello Team :wave: 
Status: Changes Required :recycle: 

Great job so far :clap: 
Let's cover the details, together ⏬

- [ ]  The file is not executable. Please make the file executable by following the source provided by the previous TSE.

- [ ]  We have a linter error, related to the file is not being executable. When we make the file executable, that error will be fixed :blush: 
:bulb: Rubocop is looking at your first line of the file and sees instructions for the executable files. And it checks the state of the file, but the file is not executable. So rubocop is warning us to whether make the file executable or delete this line. What we should do is to make the file executable.


### That's it team :blush:  After making the changes, you can request another code review.
With all my respect :pray: 
> Kubilay Caglayan | Technical Support Engineer

**Comment by janis-jenny** [comment]
Hi Kubilay. Ive already changed it I make it executable.

**Comment by kubilaycaglayan** [comment]
Hello Team :wave: 

Let me also share the screenshots with you please :blush: 

**Screenshot from command line :camera_flash:**
image


**Screenshot of file properties :camera_flash:**
image


#### We expect to see the output from `bin/main.rb` as well as `ruby bin/main.rb`. 

Be sure when you try it on your side, this is working fine :arrow_right:  `bin/main.rb`

With all my respect :pray:

**Review by kobiyoyo — APPROVED** [review]
# Project Approved :thumbsup:
## Hello Team  ,  you have done a brilliant job with this project. :clap:
#### You can merge !!!

**Pull request merged**
